package com.mateicrainiceanu;

public class StudentScore {
    private String studentName;
    private int score;

    public String getStudentName() {
        return studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }

    public StudentScore(String studentName, int score) {
        this.studentName = studentName;
        this.score = score;
    }
// constructor, getters and setters -> generated by IDE (Alt + Insert)
}